version: '3.8'

services:
  mysql:
    image: mysql:8 # Replace 8 with your desired MySQL version
    environment:
      MYSQL_ROOT_PASSWORD: pike
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
