CREATE TABLE IF NOT EXISTS SensorType (
	Id INT NOT NULL UNIQUE AUTO_INCREMENT,
	TypeName VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS SensorTypeData (
	Id INT NOT NULL UNIQUE AUTO_INCREMENT,
	SensorTypeId INT NOT NULL,
	TypeName VARCHAR(255),
	ValueType VARCHAR(255),
	PRIMARY KEY (Id),
	FOREIGN KEY (SensorTypeId) REFERENCES SensorType (Id)
);


CREATE TABLE IF NOT EXISTS SwitchType (
	Id	INT NOT NULL UNIQUE AUTO_INCREMENT,
	TypeName	VARCHAR(255) UNIQUE,
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS Node (
	Id	INT NOT NULL UNIQUE AUTO_INCREMENT,
	Mac	CHAR(12) UNIQUE,
	NodeName	VARCHAR(255) UNIQUE,
	IpAddress VARCHAR(15) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS NodeSensor (
	Id	INT NOT NULL UNIQUE AUTO_INCREMENT,
	NodeId	INT NOT NULL,
	SensorTypeId	INT NOT NULL,
	SensorName	VARCHAR(255) NOT NULL,
	Pin	INT NOT NULL,
	DHTType	INT,
	FOREIGN KEY(NodeId) REFERENCES Node(Id),
	FOREIGN KEY(SensorTypeId) REFERENCES SensorType(Id),
	PRIMARY KEY(Id)
)

CREATE TABLE IF NOT EXISTS NodeSwitch (
	Id	INT NOT NULL UNIQUE AUTO_INCREMENT,
	NodeId	INT NOT NULL,
	SwitchTypeId	INT NOT NULL,
	SwitchName	VARCHAR(255) NOT NULL,
	Pin	INT NOT NULL,
	MomentaryPressDuration	INT DEFAULT 100,
	IsClosedOn	INT DEFAULT 1,
	FOREIGN KEY(NodeId) REFERENCES Node(Id),
	FOREIGN KEY(SwitchTypeId) REFERENCES SwitchType(Id),
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS ControlPoint (
	Id	INT NOT NULL UNIQUE AUTO_INCREMENT,
	PointName	VARCHAR(255) NOT NULL,
	IpAddress	VARCHAR(15) NOT NULL,
	Mac	CHAR(12) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS ControlPointNodes (
	Id	INT NOT NULL UNIQUE AUTO_INCREMENT,
	ControlPointId	INT NOT NULL,
	NodeId	INT NOT NULL,
	FOREIGN KEY(NodeId) REFERENCES Node(Id),
	FOREIGN KEY(ControlPointId) REFERENCES ControlPoint(Id),
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS View (
	Id	INT NOT NULL UNIQUE AUTO_INCREMENT,
	ViewName	VARCHAR(512) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS ViewNodeSensorData (
	Id	INT NOT NULL UNIQUE AUTO_INCREMENT,
	NodeId	INT NOT NULL UNIQUE,
	ViewId	INT NOT NULL UNIQUE,
	NodeSensorId	INT NOT NULL UNIQUE,
	DataName	VARCHAR(255) NOT NULL,
	FOREIGN KEY(NodeId) REFERENCES Node(Id),
	FOREIGN KEY(ViewId) REFERENCES View(Id),
	FOREIGN KEY(NodeSensorId) REFERENCES NodeSensor(Id),
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS ViewNodeSwitchData (
	Id	INT NOT NULL UNIQUE AUTO_INCREMENT,
	NodeId	INT NOT NULL UNIQUE,
	ViewId	INT NOT NULL UNIQUE,
	NodeSwitchId	INT NOT NULL UNIQUE,
	DataName	VARCHAR(255) NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(ViewId) REFERENCES View(Id),
	FOREIGN KEY(NodeSwitchId) REFERENCES NodeSwitch(Id),
	FOREIGN KEY(NodeId) REFERENCES Node(Id)
);

CREATE TABLE IF NOT EXISTS NodeSensorLog (
    Id INT NOT NULL UNIQUE AUTO_INCREMENT,
    NodeId INT NOT NULL,
    DateLogged DATETIME NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(NodeId) REFERENCES Node(Id)
);

CREATE TABLE IF NOT EXISTS MagneticLog (
    Id INT NOT NULL UNIQUE AUTO_INCREMENT,
    NodeSensorLogId INT NOT NULL,
    IsClosed BIT NOT NULL,
	FOREIGN KEY(NodeSensorLogId) REFERENCES NodeSensorLog(Id),
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS MoistureLog (
    Id INT NOT NULL UNIQUE AUTO_INCREMENT,
    NodeSensorLogId INT NOT NULL,
    Moisture INT NOT NULL,
	FOREIGN KEY(NodeSensorLogId) REFERENCES NodeSensorLog(Id),
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS ResistorLog (
    Id INT NOT NULL UNIQUE AUTO_INCREMENT,
    NodeSensorLogId INT NOT NULL,
    ResistorValue INT NOT NULL,
	FOREIGN KEY(NodeSensorLogId) REFERENCES NodeSensorLog(Id),
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS TempLog (
    Id INT NOT NULL UNIQUE AUTO_INCREMENT,
    NodeSensorLogId INT NOT NULL,
    TemperatureF FLOAT NOT NULL,
    TemperatureC FLOAT NOT NULL,
    Humidity FLOAT NOT NULL,
	FOREIGN KEY(NodeSensorLogId) REFERENCES NodeSensorLog(Id),
	PRIMARY KEY (Id)
);

INSERT IGNORE INTO SensorType
(TypeName)
VALUES 
('DHT'),
('Moisture'),
('Magnetic'),
('Photoresistor');

INSERT IGNORE INTO SensorTypeData
(SensorTypeId, TypeName, ValueType)
VALUES (1, 'TemperatureF', 'float'),
(1, 'TemperatureC', 'float'),
(1, 'Humidity', 'float'),
(2, 'Moisture', 'int'),
(3, 'IsClosed', 'int'),
(4, 'ResistorValue', 'int');

INSERT IGNORE INTO SwitchType
(TypeName)
VALUES ('Momentary'),
('Toggle');